### ISSUE TITLE
Get request example

### ISSUE THREAD

**Issue by Phunky2018** [MichMich/OfficeDoorLight#1]
Thanks for this nice little project.
But can you add an example get request code to trigger the lights? Is it possible with every webbrowser? Or add a screenshot from the shortcut app?

**Comment by MichMich** [comment]
![image](https://user-images.githubusercontent.com/210954/124358703-c90c7380-dc21-11eb-8146-425e5104c4f1.png)

De this is the shortcut. But since it's Dutch, it probably isn't very helpful. 

With a both of luck you can download it here: 

https://www.icloud.com/shortcuts/126165048cab4c4ba60904d57f03fdeb

You might need to adjust the ip-adres. 

If you want to do it via the command line, this should probably work: 

    curl -X POST http://192.168.1.123 -d "{\"red\":true,\"orange\":false,\"green\":false}"

(Untested)

**Comment by Phunky2018** [comment]
Thank you. Now it works
